name: store
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^10.8.0
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9
  firebase_auth: ^5.6.0
  firebase_storage: ^12.4.7
  firebase_messaging: ^15.0.0
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  dotted_border: ^3.0.1
  cached_network_image: ^3.4.1
  provider: ^6.1.5
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  dio: ^5.7.0
  get_it: ^7.7.0
  dartz: ^0.10.1
  flutter_stripe: ^10.1.1
  fl_chart: ^0.69.0
  video_player: ^2.9.1

  intl: ^0.19.0
  gal: ^2.3.0
  permission_handler: ^11.3.1
  ar_flutter_plugin_2: ^0.0.3
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
     - assets/image/images.png
 
flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/images.png"
