// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM1CgL4QvyhvLi1qsXHN7f3uTgwDoSVEU',
    appId: '1:316435715817:web:6e8fbe736eba20129b0278',
    messagingSenderId: '316435715817',
    projectId: 'storeapp-firebase',
    authDomain: 'storeapp-firebase.firebaseapp.com',
    storageBucket: 'storeapp-firebase.firebasestorage.app',
    measurementId: 'G-47TJ4Q89Q1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMQ4IS8dF4rLD88QVZbC9a26-Z01H0VTQ',
    appId: '1:316435715817:android:54ea331738a669379b0278',
    messagingSenderId: '316435715817',
    projectId: 'storeapp-firebase',
    storageBucket: 'storeapp-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtMpN33IhgIgvVD0YbrGO1Q3sWyZ3S2K4',
    appId: '1:316435715817:ios:6edbd553aa6462389b0278',
    messagingSenderId: '316435715817',
    projectId: 'storeapp-firebase',
    storageBucket: 'storeapp-firebase.firebasestorage.app',
    iosBundleId: 'com.example.store',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtMpN33IhgIgvVD0YbrGO1Q3sWyZ3S2K4',
    appId: '1:316435715817:ios:6edbd553aa6462389b0278',
    messagingSenderId: '316435715817',
    projectId: 'storeapp-firebase',
    storageBucket: 'storeapp-firebase.firebasestorage.app',
    iosBundleId: 'com.example.store',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM1CgL4QvyhvLi1qsXHN7f3uTgwDoSVEU',
    appId: '1:316435715817:web:1987157f960469e19b0278',
    messagingSenderId: '316435715817',
    projectId: 'storeapp-firebase',
    authDomain: 'storeapp-firebase.firebaseapp.com',
    storageBucket: 'storeapp-firebase.firebasestorage.app',
    measurementId: 'G-379V1EFLEN',
  );
}
